services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      - GOFLAGS=-buildvcs=false
    env_file: ".env"
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:18.3
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: echodb
    ports:
      - 5432:5432
    attach: false
    volumes:
      - postgres_data:/var/lib/postgres/data

volumes:
  postgres_data:
