services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./
      target: development
    environment:
      - GOFLAGS=-buildvcs=false
    env_file: ".env"
    volumes:
      - ./:/app
    networks:
      - ripple-network
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis

  web:
    build:
      dockerfile: Dockerfile
      context: ./web/
      target: development
    ports:
      - 5173:5173
    volumes:
      - ./web:/app
      - /app/node_modules
    networks:
      - ripple-network

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rippledb
    attach: false
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ripple-network

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ripple-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  ripple-network:
    driver: bridge
