// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	models "github.com/h1divp/echo-chat-v2/internal/db/models"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type AuthUserMod interface {
	Apply(context.Context, *AuthUserTemplate)
}

type AuthUserModFunc func(context.Context, *AuthUserTemplate)

func (f AuthUserModFunc) Apply(ctx context.Context, n *AuthUserTemplate) {
	f(ctx, n)
}

type AuthUserModSlice []AuthUserMod

func (mods AuthUserModSlice) Apply(ctx context.Context, n *AuthUserTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// AuthUserTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type AuthUserTemplate struct {
	ID            func() uuid.UUID
	Email         func() string
	EmailVerified func() bool
	CreatedAt     func() time.Time
	UpdatedAt     func() time.Time

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the AuthUserTemplate
func (o *AuthUserTemplate) Apply(ctx context.Context, mods ...AuthUserMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.AuthUser
// according to the relationships in the template. Nothing is inserted into the db
func (t AuthUserTemplate) setModelRels(o *models.AuthUser) {}

// BuildSetter returns an *models.AuthUserSetter
// this does nothing with the relationship templates
func (o AuthUserTemplate) BuildSetter() *models.AuthUserSetter {
	m := &models.AuthUserSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Email != nil {
		val := o.Email()
		m.Email = omit.From(val)
	}
	if o.EmailVerified != nil {
		val := o.EmailVerified()
		m.EmailVerified = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.AuthUserSetter
// this does nothing with the relationship templates
func (o AuthUserTemplate) BuildManySetter(number int) []*models.AuthUserSetter {
	m := make([]*models.AuthUserSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.AuthUser
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use AuthUserTemplate.Create
func (o AuthUserTemplate) Build() *models.AuthUser {
	m := &models.AuthUser{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Email != nil {
		m.Email = o.Email()
	}
	if o.EmailVerified != nil {
		m.EmailVerified = o.EmailVerified()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.AuthUserSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use AuthUserTemplate.CreateMany
func (o AuthUserTemplate) BuildMany(number int) models.AuthUserSlice {
	m := make(models.AuthUserSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableAuthUser(m *models.AuthUserSetter) {
	if !(m.Email.IsValue()) {
		val := random_string(nil)
		m.Email = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.AuthUser
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *AuthUserTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.AuthUser) error {
	var err error

	return err
}

// Create builds a authUser and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *AuthUserTemplate) Create(ctx context.Context, exec bob.Executor) (*models.AuthUser, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableAuthUser(opt)

	m, err := models.AuthUsers.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a authUser and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *AuthUserTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.AuthUser {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a authUser and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *AuthUserTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.AuthUser {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple authUsers and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o AuthUserTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.AuthUserSlice, error) {
	var err error
	m := make(models.AuthUserSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple authUsers and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o AuthUserTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.AuthUserSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple authUsers and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o AuthUserTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.AuthUserSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// AuthUser has methods that act as mods for the AuthUserTemplate
var AuthUserMods authUserMods

type authUserMods struct{}

func (m authUserMods) RandomizeAllColumns(f *faker.Faker) AuthUserMod {
	return AuthUserModSlice{
		AuthUserMods.RandomID(f),
		AuthUserMods.RandomEmail(f),
		AuthUserMods.RandomEmailVerified(f),
		AuthUserMods.RandomCreatedAt(f),
		AuthUserMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m authUserMods) ID(val uuid.UUID) AuthUserMod {
	return AuthUserModFunc(func(_ context.Context, o *AuthUserTemplate) {
		o.ID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m authUserMods) IDFunc(f func() uuid.UUID) AuthUserMod {
	return AuthUserModFunc(func(_ context.Context, o *AuthUserTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m authUserMods) UnsetID() AuthUserMod {
	return AuthUserModFunc(func(_ context.Context, o *AuthUserTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m authUserMods) RandomID(f *faker.Faker) AuthUserMod {
	return AuthUserModFunc(func(_ context.Context, o *AuthUserTemplate) {
		o.ID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m authUserMods) Email(val string) AuthUserMod {
	return AuthUserModFunc(func(_ context.Context, o *AuthUserTemplate) {
		o.Email = func() string { return val }
	})
}

// Set the Column from the function
func (m authUserMods) EmailFunc(f func() string) AuthUserMod {
	return AuthUserModFunc(func(_ context.Context, o *AuthUserTemplate) {
		o.Email = f
	})
}

// Clear any values for the column
func (m authUserMods) UnsetEmail() AuthUserMod {
	return AuthUserModFunc(func(_ context.Context, o *AuthUserTemplate) {
		o.Email = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m authUserMods) RandomEmail(f *faker.Faker) AuthUserMod {
	return AuthUserModFunc(func(_ context.Context, o *AuthUserTemplate) {
		o.Email = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m authUserMods) EmailVerified(val bool) AuthUserMod {
	return AuthUserModFunc(func(_ context.Context, o *AuthUserTemplate) {
		o.EmailVerified = func() bool { return val }
	})
}

// Set the Column from the function
func (m authUserMods) EmailVerifiedFunc(f func() bool) AuthUserMod {
	return AuthUserModFunc(func(_ context.Context, o *AuthUserTemplate) {
		o.EmailVerified = f
	})
}

// Clear any values for the column
func (m authUserMods) UnsetEmailVerified() AuthUserMod {
	return AuthUserModFunc(func(_ context.Context, o *AuthUserTemplate) {
		o.EmailVerified = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m authUserMods) RandomEmailVerified(f *faker.Faker) AuthUserMod {
	return AuthUserModFunc(func(_ context.Context, o *AuthUserTemplate) {
		o.EmailVerified = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m authUserMods) CreatedAt(val time.Time) AuthUserMod {
	return AuthUserModFunc(func(_ context.Context, o *AuthUserTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m authUserMods) CreatedAtFunc(f func() time.Time) AuthUserMod {
	return AuthUserModFunc(func(_ context.Context, o *AuthUserTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m authUserMods) UnsetCreatedAt() AuthUserMod {
	return AuthUserModFunc(func(_ context.Context, o *AuthUserTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m authUserMods) RandomCreatedAt(f *faker.Faker) AuthUserMod {
	return AuthUserModFunc(func(_ context.Context, o *AuthUserTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m authUserMods) UpdatedAt(val time.Time) AuthUserMod {
	return AuthUserModFunc(func(_ context.Context, o *AuthUserTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m authUserMods) UpdatedAtFunc(f func() time.Time) AuthUserMod {
	return AuthUserModFunc(func(_ context.Context, o *AuthUserTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m authUserMods) UnsetUpdatedAt() AuthUserMod {
	return AuthUserModFunc(func(_ context.Context, o *AuthUserTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m authUserMods) RandomUpdatedAt(f *faker.Faker) AuthUserMod {
	return AuthUserModFunc(func(_ context.Context, o *AuthUserTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m authUserMods) WithParentsCascading() AuthUserMod {
	return AuthUserModFunc(func(ctx context.Context, o *AuthUserTemplate) {
		if isDone, _ := authUserWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = authUserWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
