// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"

	models "github.com/h1divp/echo-chat-v2/internal/db/models"
)

type Factory struct {
	baseGooseDBVersionMods GooseDBVersionModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewGooseDBVersion(mods ...GooseDBVersionMod) *GooseDBVersionTemplate {
	return f.NewGooseDBVersionWithContext(context.Background(), mods...)
}

func (f *Factory) NewGooseDBVersionWithContext(ctx context.Context, mods ...GooseDBVersionMod) *GooseDBVersionTemplate {
	o := &GooseDBVersionTemplate{f: f}

	if f != nil {
		f.baseGooseDBVersionMods.Apply(ctx, o)
	}

	GooseDBVersionModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingGooseDBVersion(m *models.GooseDBVersion) *GooseDBVersionTemplate {
	o := &GooseDBVersionTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int32 { return m.ID }
	o.VersionID = func() int64 { return m.VersionID }
	o.IsApplied = func() bool { return m.IsApplied }
	o.Tstamp = func() time.Time { return m.Tstamp }

	return o
}

func (f *Factory) ClearBaseGooseDBVersionMods() {
	f.baseGooseDBVersionMods = nil
}

func (f *Factory) AddBaseGooseDBVersionMod(mods ...GooseDBVersionMod) {
	f.baseGooseDBVersionMods = append(f.baseGooseDBVersionMods, mods...)
}
