// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var AuthUserErrors = &authUserErrors{
	ErrUniqueUsersPkey: &UniqueConstraintError{
		schema:  "auth",
		table:   "users",
		columns: []string{"id"},
		s:       "users_pkey",
	},

	ErrUniqueUsersEmailKey: &UniqueConstraintError{
		schema:  "auth",
		table:   "users",
		columns: []string{"email"},
		s:       "users_email_key",
	},
}

type authUserErrors struct {
	ErrUniqueUsersPkey *UniqueConstraintError

	ErrUniqueUsersEmailKey *UniqueConstraintError
}
