services:
  # IMAGE_TAG_STAGING and IMAGE_TAG_PROD are injected as environment variables during deployment/promotion
  api-staging:
    image: ghcr.io/h1divp/ripple/api:${IMAGE_TAG_STAGING}
    ports:
      - "8081:8080"
    restart: always
    networks:
      - api-network

  api-production:
    image: ghcr.io/h1divp/ripple/api:${IMAGE_TAG_PROD}
    ports:
      - "8080:8080"
    restart: always
    networks:
      - api-network

# volumes:
#   caddy_data:
#   caddy_config:

networks:
  api-network:
    driver: bridge
