// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"

	"github.com/gofrs/uuid/v5"
	models "github.com/h1divp/echo-chat-v2/internal/db/models"
)

type Factory struct {
	baseAuthUserMods             AuthUserModSlice
	basePublicGooseDBVersionMods PublicGooseDBVersionModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewAuthUser(mods ...AuthUserMod) *AuthUserTemplate {
	return f.NewAuthUserWithContext(context.Background(), mods...)
}

func (f *Factory) NewAuthUserWithContext(ctx context.Context, mods ...AuthUserMod) *AuthUserTemplate {
	o := &AuthUserTemplate{f: f}

	if f != nil {
		f.baseAuthUserMods.Apply(ctx, o)
	}

	AuthUserModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingAuthUser(m *models.AuthUser) *AuthUserTemplate {
	o := &AuthUserTemplate{f: f, alreadyPersisted: true}

	o.ID = func() uuid.UUID { return m.ID }
	o.Email = func() string { return m.Email }
	o.EmailVerified = func() bool { return m.EmailVerified }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	return o
}

func (f *Factory) NewPublicGooseDBVersion(mods ...PublicGooseDBVersionMod) *PublicGooseDBVersionTemplate {
	return f.NewPublicGooseDBVersionWithContext(context.Background(), mods...)
}

func (f *Factory) NewPublicGooseDBVersionWithContext(ctx context.Context, mods ...PublicGooseDBVersionMod) *PublicGooseDBVersionTemplate {
	o := &PublicGooseDBVersionTemplate{f: f}

	if f != nil {
		f.basePublicGooseDBVersionMods.Apply(ctx, o)
	}

	PublicGooseDBVersionModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingPublicGooseDBVersion(m *models.PublicGooseDBVersion) *PublicGooseDBVersionTemplate {
	o := &PublicGooseDBVersionTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int32 { return m.ID }
	o.VersionID = func() int64 { return m.VersionID }
	o.IsApplied = func() bool { return m.IsApplied }
	o.Tstamp = func() time.Time { return m.Tstamp }

	return o
}

func (f *Factory) ClearBaseAuthUserMods() {
	f.baseAuthUserMods = nil
}

func (f *Factory) AddBaseAuthUserMod(mods ...AuthUserMod) {
	f.baseAuthUserMods = append(f.baseAuthUserMods, mods...)
}

func (f *Factory) ClearBasePublicGooseDBVersionMods() {
	f.basePublicGooseDBVersionMods = nil
}

func (f *Factory) AddBasePublicGooseDBVersionMod(mods ...PublicGooseDBVersionMod) {
	f.basePublicGooseDBVersionMods = append(f.basePublicGooseDBVersionMods, mods...)
}
