// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/omit"
	models "github.com/h1divp/echo-chat-v2/internal/db/models"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type PublicGooseDBVersionMod interface {
	Apply(context.Context, *PublicGooseDBVersionTemplate)
}

type PublicGooseDBVersionModFunc func(context.Context, *PublicGooseDBVersionTemplate)

func (f PublicGooseDBVersionModFunc) Apply(ctx context.Context, n *PublicGooseDBVersionTemplate) {
	f(ctx, n)
}

type PublicGooseDBVersionModSlice []PublicGooseDBVersionMod

func (mods PublicGooseDBVersionModSlice) Apply(ctx context.Context, n *PublicGooseDBVersionTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// PublicGooseDBVersionTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type PublicGooseDBVersionTemplate struct {
	ID        func() int32
	VersionID func() int64
	IsApplied func() bool
	Tstamp    func() time.Time

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the PublicGooseDBVersionTemplate
func (o *PublicGooseDBVersionTemplate) Apply(ctx context.Context, mods ...PublicGooseDBVersionMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.PublicGooseDBVersion
// according to the relationships in the template. Nothing is inserted into the db
func (t PublicGooseDBVersionTemplate) setModelRels(o *models.PublicGooseDBVersion) {}

// BuildSetter returns an *models.PublicGooseDBVersionSetter
// this does nothing with the relationship templates
func (o PublicGooseDBVersionTemplate) BuildSetter() *models.PublicGooseDBVersionSetter {
	m := &models.PublicGooseDBVersionSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.VersionID != nil {
		val := o.VersionID()
		m.VersionID = omit.From(val)
	}
	if o.IsApplied != nil {
		val := o.IsApplied()
		m.IsApplied = omit.From(val)
	}
	if o.Tstamp != nil {
		val := o.Tstamp()
		m.Tstamp = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.PublicGooseDBVersionSetter
// this does nothing with the relationship templates
func (o PublicGooseDBVersionTemplate) BuildManySetter(number int) []*models.PublicGooseDBVersionSetter {
	m := make([]*models.PublicGooseDBVersionSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.PublicGooseDBVersion
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use PublicGooseDBVersionTemplate.Create
func (o PublicGooseDBVersionTemplate) Build() *models.PublicGooseDBVersion {
	m := &models.PublicGooseDBVersion{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.VersionID != nil {
		m.VersionID = o.VersionID()
	}
	if o.IsApplied != nil {
		m.IsApplied = o.IsApplied()
	}
	if o.Tstamp != nil {
		m.Tstamp = o.Tstamp()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.PublicGooseDBVersionSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use PublicGooseDBVersionTemplate.CreateMany
func (o PublicGooseDBVersionTemplate) BuildMany(number int) models.PublicGooseDBVersionSlice {
	m := make(models.PublicGooseDBVersionSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatablePublicGooseDBVersion(m *models.PublicGooseDBVersionSetter) {
	if !(m.VersionID.IsValue()) {
		val := random_int64(nil)
		m.VersionID = omit.From(val)
	}
	if !(m.IsApplied.IsValue()) {
		val := random_bool(nil)
		m.IsApplied = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.PublicGooseDBVersion
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *PublicGooseDBVersionTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.PublicGooseDBVersion) error {
	var err error

	return err
}

// Create builds a publicGooseDBVersion and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *PublicGooseDBVersionTemplate) Create(ctx context.Context, exec bob.Executor) (*models.PublicGooseDBVersion, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatablePublicGooseDBVersion(opt)

	m, err := models.PublicGooseDBVersions.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a publicGooseDBVersion and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *PublicGooseDBVersionTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.PublicGooseDBVersion {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a publicGooseDBVersion and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *PublicGooseDBVersionTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.PublicGooseDBVersion {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple publicGooseDBVersions and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o PublicGooseDBVersionTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.PublicGooseDBVersionSlice, error) {
	var err error
	m := make(models.PublicGooseDBVersionSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple publicGooseDBVersions and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o PublicGooseDBVersionTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.PublicGooseDBVersionSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple publicGooseDBVersions and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o PublicGooseDBVersionTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.PublicGooseDBVersionSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// PublicGooseDBVersion has methods that act as mods for the PublicGooseDBVersionTemplate
var PublicGooseDBVersionMods publicGooseDBVersionMods

type publicGooseDBVersionMods struct{}

func (m publicGooseDBVersionMods) RandomizeAllColumns(f *faker.Faker) PublicGooseDBVersionMod {
	return PublicGooseDBVersionModSlice{
		PublicGooseDBVersionMods.RandomID(f),
		PublicGooseDBVersionMods.RandomVersionID(f),
		PublicGooseDBVersionMods.RandomIsApplied(f),
		PublicGooseDBVersionMods.RandomTstamp(f),
	}
}

// Set the model columns to this value
func (m publicGooseDBVersionMods) ID(val int32) PublicGooseDBVersionMod {
	return PublicGooseDBVersionModFunc(func(_ context.Context, o *PublicGooseDBVersionTemplate) {
		o.ID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m publicGooseDBVersionMods) IDFunc(f func() int32) PublicGooseDBVersionMod {
	return PublicGooseDBVersionModFunc(func(_ context.Context, o *PublicGooseDBVersionTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m publicGooseDBVersionMods) UnsetID() PublicGooseDBVersionMod {
	return PublicGooseDBVersionModFunc(func(_ context.Context, o *PublicGooseDBVersionTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m publicGooseDBVersionMods) RandomID(f *faker.Faker) PublicGooseDBVersionMod {
	return PublicGooseDBVersionModFunc(func(_ context.Context, o *PublicGooseDBVersionTemplate) {
		o.ID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m publicGooseDBVersionMods) VersionID(val int64) PublicGooseDBVersionMod {
	return PublicGooseDBVersionModFunc(func(_ context.Context, o *PublicGooseDBVersionTemplate) {
		o.VersionID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m publicGooseDBVersionMods) VersionIDFunc(f func() int64) PublicGooseDBVersionMod {
	return PublicGooseDBVersionModFunc(func(_ context.Context, o *PublicGooseDBVersionTemplate) {
		o.VersionID = f
	})
}

// Clear any values for the column
func (m publicGooseDBVersionMods) UnsetVersionID() PublicGooseDBVersionMod {
	return PublicGooseDBVersionModFunc(func(_ context.Context, o *PublicGooseDBVersionTemplate) {
		o.VersionID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m publicGooseDBVersionMods) RandomVersionID(f *faker.Faker) PublicGooseDBVersionMod {
	return PublicGooseDBVersionModFunc(func(_ context.Context, o *PublicGooseDBVersionTemplate) {
		o.VersionID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m publicGooseDBVersionMods) IsApplied(val bool) PublicGooseDBVersionMod {
	return PublicGooseDBVersionModFunc(func(_ context.Context, o *PublicGooseDBVersionTemplate) {
		o.IsApplied = func() bool { return val }
	})
}

// Set the Column from the function
func (m publicGooseDBVersionMods) IsAppliedFunc(f func() bool) PublicGooseDBVersionMod {
	return PublicGooseDBVersionModFunc(func(_ context.Context, o *PublicGooseDBVersionTemplate) {
		o.IsApplied = f
	})
}

// Clear any values for the column
func (m publicGooseDBVersionMods) UnsetIsApplied() PublicGooseDBVersionMod {
	return PublicGooseDBVersionModFunc(func(_ context.Context, o *PublicGooseDBVersionTemplate) {
		o.IsApplied = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m publicGooseDBVersionMods) RandomIsApplied(f *faker.Faker) PublicGooseDBVersionMod {
	return PublicGooseDBVersionModFunc(func(_ context.Context, o *PublicGooseDBVersionTemplate) {
		o.IsApplied = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m publicGooseDBVersionMods) Tstamp(val time.Time) PublicGooseDBVersionMod {
	return PublicGooseDBVersionModFunc(func(_ context.Context, o *PublicGooseDBVersionTemplate) {
		o.Tstamp = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m publicGooseDBVersionMods) TstampFunc(f func() time.Time) PublicGooseDBVersionMod {
	return PublicGooseDBVersionModFunc(func(_ context.Context, o *PublicGooseDBVersionTemplate) {
		o.Tstamp = f
	})
}

// Clear any values for the column
func (m publicGooseDBVersionMods) UnsetTstamp() PublicGooseDBVersionMod {
	return PublicGooseDBVersionModFunc(func(_ context.Context, o *PublicGooseDBVersionTemplate) {
		o.Tstamp = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m publicGooseDBVersionMods) RandomTstamp(f *faker.Faker) PublicGooseDBVersionMod {
	return PublicGooseDBVersionModFunc(func(_ context.Context, o *PublicGooseDBVersionTemplate) {
		o.Tstamp = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m publicGooseDBVersionMods) WithParentsCascading() PublicGooseDBVersionMod {
	return PublicGooseDBVersionModFunc(func(ctx context.Context, o *PublicGooseDBVersionTemplate) {
		if isDone, _ := publicGooseDBVersionWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = publicGooseDBVersionWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
