// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var PublicGooseDBVersionErrors = &publicGooseDBVersionErrors{
	ErrUniqueGooseDbVersionPkey: &UniqueConstraintError{
		schema:  "public",
		table:   "goose_db_version",
		columns: []string{"id"},
		s:       "goose_db_version_pkey",
	},
}

type publicGooseDBVersionErrors struct {
	ErrUniqueGooseDbVersionPkey *UniqueConstraintError
}
