// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
)

// AuthUser is an object representing the database table.
type AuthUser struct {
	ID            uuid.UUID `db:"id,pk" `
	Email         string    `db:"email" `
	EmailVerified bool      `db:"email_verified" `
	CreatedAt     time.Time `db:"created_at" `
	UpdatedAt     time.Time `db:"updated_at" `
}

// AuthUserSlice is an alias for a slice of pointers to AuthUser.
// This should almost always be used instead of []*AuthUser.
type AuthUserSlice []*AuthUser

// AuthUsers contains methods to work with the users table
var AuthUsers = psql.NewTablex[*AuthUser, AuthUserSlice, *AuthUserSetter]("auth", "users", buildAuthUserColumns("auth.users"))

// AuthUsersQuery is a query on the users table
type AuthUsersQuery = *psql.ViewQuery[*AuthUser, AuthUserSlice]

func buildAuthUserColumns(alias string) authUserColumns {
	return authUserColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "email", "email_verified", "created_at", "updated_at",
		).WithParent("auth.users"),
		tableAlias:    alias,
		ID:            psql.Quote(alias, "id"),
		Email:         psql.Quote(alias, "email"),
		EmailVerified: psql.Quote(alias, "email_verified"),
		CreatedAt:     psql.Quote(alias, "created_at"),
		UpdatedAt:     psql.Quote(alias, "updated_at"),
	}
}

type authUserColumns struct {
	expr.ColumnsExpr
	tableAlias    string
	ID            psql.Expression
	Email         psql.Expression
	EmailVerified psql.Expression
	CreatedAt     psql.Expression
	UpdatedAt     psql.Expression
}

func (c authUserColumns) Alias() string {
	return c.tableAlias
}

func (authUserColumns) AliasedAs(alias string) authUserColumns {
	return buildAuthUserColumns(alias)
}

// AuthUserSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type AuthUserSetter struct {
	ID            omit.Val[uuid.UUID] `db:"id,pk" `
	Email         omit.Val[string]    `db:"email" `
	EmailVerified omit.Val[bool]      `db:"email_verified" `
	CreatedAt     omit.Val[time.Time] `db:"created_at" `
	UpdatedAt     omit.Val[time.Time] `db:"updated_at" `
}

func (s AuthUserSetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Email.IsValue() {
		vals = append(vals, "email")
	}
	if s.EmailVerified.IsValue() {
		vals = append(vals, "email_verified")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s AuthUserSetter) Overwrite(t *AuthUser) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Email.IsValue() {
		t.Email = s.Email.MustGet()
	}
	if s.EmailVerified.IsValue() {
		t.EmailVerified = s.EmailVerified.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *AuthUserSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return AuthUsers.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 5)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Email.IsValue() {
			vals[1] = psql.Arg(s.Email.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.EmailVerified.IsValue() {
			vals[2] = psql.Arg(s.EmailVerified.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[3] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[4] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s AuthUserSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s AuthUserSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Email.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "email")...),
			psql.Arg(s.Email),
		}})
	}

	if s.EmailVerified.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "email_verified")...),
			psql.Arg(s.EmailVerified),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindAuthUser retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindAuthUser(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*AuthUser, error) {
	if len(cols) == 0 {
		return AuthUsers.Query(
			sm.Where(AuthUsers.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return AuthUsers.Query(
		sm.Where(AuthUsers.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(AuthUsers.Columns.Only(cols...)),
	).One(ctx, exec)
}

// AuthUserExists checks the presence of a single record by primary key
func AuthUserExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return AuthUsers.Query(
		sm.Where(AuthUsers.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after AuthUser is retrieved from the database
func (o *AuthUser) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = AuthUsers.AfterSelectHooks.RunHooks(ctx, exec, AuthUserSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = AuthUsers.AfterInsertHooks.RunHooks(ctx, exec, AuthUserSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = AuthUsers.AfterUpdateHooks.RunHooks(ctx, exec, AuthUserSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = AuthUsers.AfterDeleteHooks.RunHooks(ctx, exec, AuthUserSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the AuthUser
func (o *AuthUser) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *AuthUser) pkEQ() dialect.Expression {
	return psql.Quote("auth.users", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the AuthUser
func (o *AuthUser) Update(ctx context.Context, exec bob.Executor, s *AuthUserSetter) error {
	v, err := AuthUsers.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single AuthUser record with an executor
func (o *AuthUser) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := AuthUsers.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the AuthUser using the executor
func (o *AuthUser) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := AuthUsers.Query(
		sm.Where(AuthUsers.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after AuthUserSlice is retrieved from the database
func (o AuthUserSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = AuthUsers.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = AuthUsers.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = AuthUsers.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = AuthUsers.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o AuthUserSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("auth.users", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o AuthUserSlice) copyMatchingRows(from ...*AuthUser) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o AuthUserSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return AuthUsers.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *AuthUser:
				o.copyMatchingRows(retrieved)
			case []*AuthUser:
				o.copyMatchingRows(retrieved...)
			case AuthUserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a AuthUser or a slice of AuthUser
				// then run the AfterUpdateHooks on the slice
				_, err = AuthUsers.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o AuthUserSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return AuthUsers.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *AuthUser:
				o.copyMatchingRows(retrieved)
			case []*AuthUser:
				o.copyMatchingRows(retrieved...)
			case AuthUserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a AuthUser or a slice of AuthUser
				// then run the AfterDeleteHooks on the slice
				_, err = AuthUsers.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o AuthUserSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals AuthUserSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := AuthUsers.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o AuthUserSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := AuthUsers.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o AuthUserSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := AuthUsers.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type authUserWhere[Q psql.Filterable] struct {
	ID            psql.WhereMod[Q, uuid.UUID]
	Email         psql.WhereMod[Q, string]
	EmailVerified psql.WhereMod[Q, bool]
	CreatedAt     psql.WhereMod[Q, time.Time]
	UpdatedAt     psql.WhereMod[Q, time.Time]
}

func (authUserWhere[Q]) AliasedAs(alias string) authUserWhere[Q] {
	return buildAuthUserWhere[Q](buildAuthUserColumns(alias))
}

func buildAuthUserWhere[Q psql.Filterable](cols authUserColumns) authUserWhere[Q] {
	return authUserWhere[Q]{
		ID:            psql.Where[Q, uuid.UUID](cols.ID),
		Email:         psql.Where[Q, string](cols.Email),
		EmailVerified: psql.Where[Q, bool](cols.EmailVerified),
		CreatedAt:     psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:     psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}
